name: check-polls

# run every 15 minutes
on:
  schedule:
    - cron: '*/15 13-23 * * *'
    - cron: '*/15 0-3 * * *'

jobs:
  check-polls:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Decrypt large secret
        run: ./decrypt_secret.sh
        env:
          ENCRYPT_PASSPHRASE: ${{ secrets.ENCRYPT_PASSPHRASE }}
      - name: Setup Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Requirements
        run: pip install -r requirements.txt
      - name: Run poll-checking script
        run: python script.py
        env:
         ENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
         RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Evan Haldane
          author_email: evanhaldane@gmail.com
          message: "Autocommit polls-initial.json"
          add: "polls-initial.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
